# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default  # Replace this with the actual pool name where your agent is registered
  demands:
  - Agent.Name -equals WINUSWSH03

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $vmPrivateIps = @('10.0.0.4', '10.0.0.5', '10.0.0.6')
      # Define the username and password
      $username = "azureadmin"
      $password = ConvertTo-SecureString "azure@12345" -AsPlainText -Force

      # Create a PSCredential object
      $credential = New-Object System.Management.Automation.PSCredential($username, $password)

      
      foreach ($ip in $vmPrivateIps) {
          Invoke-Command -ComputerName $ip -Credential $credential -ScriptBlock {
              Restart-Service -Name "wuauserv" -Force
              Write-Host "Restarted Windows Update Service on $env:COMPUTERNAME"
          } -ErrorAction Stop
      }